/* eslint-disable prettier/prettier */
// SHARED
export const SET_LOADING = 'SET_LOADING'

// Auth
export const SET_AUTH_USER = 'SET_AUTH_USER'

// USERS
export const SET_USERS = 'SET_USERS'
export const ADD_NEW_USER = 'ADD_NEW_USER'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CACHE_USER = 'CACHE_USER'

// CLIENTS
export const SET_INDIVIDUAL_CLIENTS = 'SET_INDIVIDUAL_CLIENTS'
export const ADD_INDIVIDUAL_CLIENT = 'ADD_INDIVIDUAL_CLIENT'
export const SET_CORPORATE_CLIENTS = 'SET_CORPORATE_CLIENTS'
export const ADD_CORPORATE_CLIENT = 'ADD_CORPORATE_CLIENT'
export const SET_ALL_CLIENTS = 'ADD_ALL_CLIENTS'
export const SET_SELECTED_CLIENT = 'SET_SELECTED_CLIENT'

// QUOTATIONS

export const SET_QUOTATIONS = 'SET_QUOTATIONS'
export const APPROVE_QUOTATION = 'APPROVE_QUOTATION'
export const SET_SELECTED_QUOTATION = 'SET_SELECTED_QUOTATION'
export const SET_SELECTED_RISK = 'SET_SELECTED_RISK'
export const SET_CURRENCY = 'SET_CURRENCY'
export const SET_HIGHEST_QUARTER = 'SET_HIGHEST_QUARTER'

// POLICIES

export const SET_ALL_POLICIES = 'SET_ALL_POLICIES'
export const GET_ACTIVE_POLICIES = 'GET_ACTIVE_POLICIES'
export const GET_ALL_POLICIES = 'GET_ALL_POLICIES'
export const GET_INACTIVE_POLICIES = 'GET_INACTIVE_POLICIES'
export const ACTIVATE_POLICY = 'ACTIVATE_POLICY'
export const SET_SELECTED_POLICY = 'SET_SELECTED_POLICY'
export const SET_COVER_NOTES = 'SET_COVER_NOTES'
export const CREATE_POLICY = 'CREATE_POLICY'
export const SET_CLIENT_NAMES = 'SET_CLIENT_NAMES'

    // VEHICLES
export const GET_UPDATED_INACTIVE_POLICIES = 'GET_UPDATED_INACTIVE_POLICIES'
export const GET_PREMIUM = 'GET_PREMIUM'
export const GET_TOTAL_PREMIUM = 'GET_TOTAL_PREMIUM'


// INVOICES
export const CREATE_INVOICE = 'CREATE_INVOICE'
export const SET_INVOICES = 'SET_INVOICES'
export const SET_SELECTED_INVOICE = 'SET_SELECTED_INVOICE'
export const CANCEL_INVOICE = 'CANCEL_INVOICE'
export const REINSTATE_INVOICE = 'REINSTATE_INVOICE'


// PRODUCTS
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const GET_PRODUCT_TYPES = 'GET_PRODUCT_TYPES'

// CLASSES
export const SET_CLASSES = 'SET_CLASSES'

// TRANSACTIONS
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS'

// EXTERNAL SERVICES
export const SET_COUNTRIES = 'SET_COUNTRIES'
export const SET_COUNTRY_FLAG = 'SET_COUNTRY_FLAG'
export const SET_COUNTRY_CALLING_CODES = 'SET_COUNTRY_CALLING_CODES'
export const SET_COLORS = 'SET_COLORS'
export const ADD_COLOR = 'ADD_COLOR'

// REPORTS
export const SET_REPORTS = 'SET_REPORTS'